sudo: required
language: node_js
node_js:
- node

deploy:
  - provider: elasticbeanstalk
    access_key_id:
      secure: "$ACCESS_KEY"
    secret_access_key:
      secure: "$SECRET_KEY"
    region: "ap-southeast-2"
    app: "booklearner"
    env: "Booklearner-env"
    bucket_name: elasticbeanstalk-ap-southeast-2-217251434989
    on:
      branch: master

  - provider: elasticbeanstalk
    access_key_id:
      secure: $ACCESS_KEY
    secret_access_key:
      secure: "$SECRET_KEY"
    region: "ap-southeast-2"
    app: "booklearner-staging"
    env: "Booklearnerstaging-env"
    bucket_name: elasticbeanstalk-ap-southeast-2-217251434989
    on:
      branch: develop